spring.application.name=railway-booking

spring.datasource.url=jdbc:postgresql://localhost:5432/railway_booking
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
server.port=8080
jwt.secret=your-very-long-secret-key-change-this-in-production
jwt.expiration=3600000