spring.application.name=railway-booking

spring.datasource.url=jdbc:postgresql://localhost:5432/railway_booking
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=update {{if you run first time then do this}}
#spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
server.port=8080
#jwt.secret=your-very-long-secret-key-change-this-in-production
jwt.secret=eyJhbGciOiJub25lIn0.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTczNjI5MjEyNH0.
jwt.expiration=3600000
jwt.refresh-expiration=604800000

